In [60]:
##setting up my jupyter notebook
%matplotlib inline
import numpy as np
import pandas as pd
import random
import matplotlib.pyplot as plt 

<h1> Question #1</h1>
How likely is it that you roll doubles when rolling two dice? </li>

In [77]:
a_dice= np.random.choice([1,2,3,4,5,6], size=100_000)
b_dice=np.random.choice([1,2,3,4,5,6], size=100_000)
doubles=(a_dice==b_dice).mean()
print("The probability you roll doubles when rolling two dice is", doubles)

The probability you roll doubles when rolling two dice is 0.16723


<h1> Question # 2 </h1>
If you flip 8 coins, what is the probability of getting exactly 3 heads? What is the probability of getting more than 3 heads?

In [46]:
##setting up the variagbles and assigning the same vlue to 2 variables
n_trials= n_rows = 10_000
n_coins= n_cols= 8
#setting up heads ==1 and tails ==0
flip_coin= np.random.choice([1,0], n_trials*n_coins).reshape(n_rows, n_cols)
flip_coin

array([[1, 0, 0, ..., 0, 1, 1],
       [0, 0, 1, ..., 0, 1, 1],
       [1, 0, 1, ..., 0, 1, 1],
       ...,
       [1, 1, 1, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 1, 0, 0]])

In [50]:
flip_coin[0]

array([1, 0, 0, 0, 0, 0, 1, 1])

In [56]:
number_of_heads= flip_coin.sum(axis=1)
number_of_heads[0]

3

In [75]:
exactly_three=(number_of_heads == 3).mean() ##probability of getting exactly 3 heads
print("The probability of getting exactly three heads out of 8 coins is", exactly_three)

The probability of getting exactly three heads out of 8 coins is 0.213


In [76]:
more_than_three=(number_of_heads > 3).mean() ##probability of getting more than 3 heads
print("The probability of getting exactly three heads out of 8 coins is", more_than_three)

The probability of getting exactly three heads out of 8 coins is 0.643


<h1> Question # 3 </h1>
<li>There are approximitely 3 web development cohorts for every 1 data science cohort at Codeup. Assuming that Codeup randomly selects an alumni to put on a billboard, what are the odds that the two billboards I drive past both have data science students on them? </li>

In [64]:
##dividing the students into 2 groups with the probability of which student they are
student_types = np.random.choice(["Web Development", "Data Science"], size=(100_000, 2), p=[.75, .25])

In [65]:
##making a datafram that connects student types and billboards on the way to work
billboards = pd.DataFrame(student_types)
billboards.columns = ["first_billboard", "second_billboard"]
billboards.head()

first_billboard second_billboard
0  Web Development  Web Development
1  Web Development  Web Development
2  Web Development  Web Development
3     Data Science  Web Development
4  Web Development  Web Development

In [73]:
billboards["both_ds"] = (billboards.first_billboard == "Data Science") & (billboards.second_billboard == "Data Science")
both_ds= billboards["both_ds"].mean()
print("The probability of both billboards being data science students is", both_ds)

The probability of both billboards being data science students is 0.06297


<h1> Question # 4 </h1>
<li>Codeup students buy, on average, 3 poptart packages (+- 1.5) a day from the snack vending machine. If on monday the machine is restocked with 17 poptart packages, how likely is it that I will be able to buy some poptarts on Friday afternoon? </li>

In [78]:
##setting up the amount of poptarts sampled
poptarts = np.round(np.random.normal(3, 1.5, size=(100_000, 5)))
poptarts.mean()

3.000058

In [79]:
##arranging poptarts into an array
poptarts[0]

array([3., 4., 2., 0., 2.])

In [82]:
#determining how many poptarts are sold
poptarts_sold= poptarts.sum(axis=1)
poptarts_sold

array([11., 14., 20., ..., 19., 11., 12.])

In [85]:
poptarts_by_friday=(poptarts_sold < 17).mean()
print("The probability there will be poptarts by Friday is", poptarts_by_friday)

The probability there will be poptarts by Friday is 0.669


<h1> Question # 5 </h1>
    <ul>
<li>Men have an average height of 178 cm and standard deviation of 8cm.</li>
<li>Women have a mean of 170, sd = 6cm.</li>
<li>If a man and woman are chosen at random, P(woman taller than man)?</li>
    </ul>

<h1> Question # 6</h1>
<li>When installing anaconda on a student's computer, there's a 1 in 250 chance that the download is corrupted and the installation fails. 
    <ul>
      <li>  What are the odds that after having 50 students download anaconda, no one has an installation issue? 100 students?</li>
<li>What is the probability that we observe an installation issue within the first 150 students that download anaconda?</li>
        <li>How likely is it that 450 students all download anaconda without an issue?</li></ul>

<h1> Question # 7</h1>
<li> There's a 70% chance on any given day that there will be at least one food truck at Travis Park. However, you haven't seen a food truck there in 3 days. 
    <ul>
        <li>How unlikely is this?</li>
        <li>How likely is it that a food truck will show up sometime this week? </li></ul>

In [24]:
## setting up simulated days where food truck may be present
p_food = .7 ## 70% chance
ndays = ncols = 7 # 7 days per week
food_trucks = nrows = 10**5
food_trucks

100000

In [21]:
##calculating the probability of having a food truck present at travis park
food = np.random.random((nrows, ncols))
food

array([[0.59572093, 0.45732153, 0.98793252, ..., 0.20184298, 0.88043186,
        0.77424335],
       [0.15191609, 0.31354619, 0.60556524, ..., 0.80622332, 0.0217862 ,
        0.25613227],
       [0.75907199, 0.78487179, 0.55625964, ..., 0.55200351, 0.8976438 ,
        0.66379811],
       ...,
       [0.73959478, 0.47455181, 0.578828  , ..., 0.25836004, 0.99804422,
        0.7350159 ],
       [0.4592678 , 0.33959034, 0.99602628, ..., 0.60771105, 0.60340649,
        0.54150399],
       [0.58770118, 0.11307632, 0.78634738, ..., 0.20543622, 0.07460487,
        0.97108191]])

In [26]:
##converting probability to a bool
travis_park = food < p_food
travis_park

array([[ True,  True, False, ...,  True, False, False],
       [ True,  True,  True, ..., False,  True,  True],
       [False, False,  True, ...,  True, False,  True],
       ...,
       [False,  True,  True, ...,  True, False, False],
       [ True,  True, False, ...,  True,  True,  True],
       [ True,  True, False, ...,  True,  True, False]])

In [27]:
(travis_park.sum(axis=1) >= 1).mean() ##probability that there will be a food truck on any given day

0.9997

In [28]:
(travis_park.sum(axis=1) == 0).mean() ##probability that there will be no food truck on any given day

0.0003

<h1> Question # 8</h1>
<li> If 23 people are in the same room, what are the odds that two of them share a birthday? What if it's 20 people? 40? </li>

In [41]:
birthday_predictor_for_twenty_three= 1- ((365*(365*23 + 1))/365**23)
birthday_predictor_for_twenty_three

1.0

In [86]:
birthday_predictor_for_twenty= 1- ((365*(365*20 + 1))/365**20)
birthday_predictor_for_twenty

1.0

In [87]:
birthday_predictor_for_forty= 1- ((365*(365*40 + 1))/365**40)
birthday_predictor_for_forty

1.0